[package]
name = "nostr-clone"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
nostr-sdk = "0.9.0"
tokio = { version = "1.23.0", features = ["macros"] }
